INSERT INTO `savsoft_qbank` (`qid`, `question_type`, `question`, `description`, `question1`, `description1`, `cid`, `lid`, `no_time_served`, `no_time_corrected`, `no_time_incorrected`, `no_time_unattempted`, `inserted_by`, `inserted_by_name`, `paragraph`, `paragraph1`, `parent_id`) VALUES
(754, 'Multiple Choice Single Answer', 'Which of these is not a river in the Garden of Eden?', 'CRK', NULL, NULL, 10, 1, 61, 24, 3, 34, 0, NULL, NULL, NULL, 0),
(755, 'Multiple Choice Single Answer', 'The prophetess through  whom God delivered his message to Judah during the time of king Josiah was ------------', 'CRK', NULL, NULL, 10, 1, 71, 12, 12, 47, 0, NULL, NULL, NULL, 0),
(756, 'Multiple Choice Single Answer', 'Dorcas was raised from death at----------', 'CRK', NULL, NULL, 10, 1, 85, 28, 9, 48, 0, NULL, NULL, NULL, 0),
(757, 'Multiple Choice Single Answer', 'The man who succeeded Judas as an apostle was-----------', 'CRK', NULL, NULL, 10, 1, 72, 23, 2, 47, 0, NULL, NULL, NULL, 0),
(758, 'Multiple Choice Single Answer', 'The parable of the good Samaritan teaches us that one&#39;s neighbor is he who', 'CRK', NULL, NULL, 10, 1, 76, 25, 0, 51, 0, NULL, NULL, NULL, 0),
(759, 'Multiple Choice Single Answer', 'The major factor in the healing miracle is------------', 'CRK', NULL, NULL, 10, 1, 72, 31, 0, 41, 0, NULL, NULL, NULL, 0),
(760, 'Multiple Choice Single Answer', 'Discovering that Jonah was the cause of their trouble the mariners-----------', 'CRK', NULL, NULL, 10, 1, 87, 42, 0, 45, 0, NULL, NULL, NULL, 0),
(761, 'Multiple Choice Single Answer', 'Solomon did not show wisdom in -------------', 'CRK', NULL, NULL, 10, 1, 65, 27, 1, 37, 0, NULL, NULL, NULL, 0),
(762, 'Multiple Choice Single Answer', 'The symbol of God&#39;s covenant with Abraham was', 'CRK', NULL, NULL, 10, 1, 60, 14, 11, 35, 0, NULL, NULL, NULL, 0),
(763, 'Multiple Choice Single Answer', 'For James, there is partiality in the church if', 'CRK', NULL, NULL, 10, 1, 67, 27, 1, 39, 0, NULL, NULL, NULL, 0),
(764, 'Multiple Choice Single Answer', '&#34;My father, if it is possible, let this cup pass from me&#34;. This cup signifies', 'CRK', NULL, NULL, 10, 1, 71, 24, 2, 45, 0, NULL, NULL, NULL, 0),
(765, 'Multiple Choice Single Answer', 'Saul&#39;s sight was restored by', 'CRK', NULL, NULL, 10, 1, 66, 25, 1, 40, 0, NULL, NULL, NULL, 0),
(766, 'Multiple Choice Single Answer', 'According to Paul, God gives us victory over death through', 'CRK', NULL, NULL, 10, 1, 71, 29, 4, 38, 0, NULL, NULL, NULL, 0),
(767, 'Multiple Choice Single Answer', 'In the parable of the weeds, the enemy who sowed weeds among the wheat was', 'CRK', NULL, NULL, 10, 1, 75, 22, 1, 52, 0, NULL, NULL, NULL, 0),
(768, 'Multiple Choice Single Answer', '&#34;Why do you seek the living among the dead?&#34; This statement was made by the', 'CRK', NULL, NULL, 10, 1, 83, 33, 1, 49, 0, NULL, NULL, NULL, 0),
(769, 'Multiple Choice Single Answer', 'Paul&#39;s example of humility in his Epistle to the Philippians is', 'CRK', NULL, NULL, 10, 1, 72, 29, 2, 41, 0, NULL, NULL, NULL, 0),
(770, 'Multiple Choice Single Answer', 'Moses was keeping the flock of his father father-in-law  on mount', 'CRK', NULL, NULL, 10, 1, 76, 28, 3, 45, 0, NULL, NULL, NULL, 0),
(771, 'Multiple Choice Single Answer', 'Which of the following signs of Jesus is a nature miracle?', 'CRK', NULL, NULL, 10, 1, 65, 20, 5, 40, 0, NULL, NULL, NULL, 0),
(772, 'Multiple Choice Single Answer', 'The agony of Jesus in the Garden of Gethsemane was a', 'CRK', NULL, NULL, 10, 1, 72, 11, 18, 43, 0, NULL, NULL, NULL, 0),
(773, 'Multiple Choice Single Answer', 'Jesus use of an ass during the triumphal entry signifies that he was', 'CRK', NULL, NULL, 10, 1, 68, 24, 4, 40, 0, NULL, NULL, NULL, 0),
(774, 'Multiple Choice Single Answer', 'Saul&#39;s war with the Amalekites was called Holy war because', 'CRK', NULL, NULL, 10, 1, 68, 25, 7, 36, 0, NULL, NULL, NULL, 0),
(775, 'Multiple Choice Single Answer', 'In the creation account, the job of giving names to all living creatures was done by', 'CRK', NULL, NULL, 10, 1, 64, 7, 19, 38, 0, NULL, NULL, NULL, 0),
(776, 'Multiple Choice Single Answer', 'Which of the following false charges were leveled against Jesus before Caiaphas the High Priest?  That he', 'CRK', NULL, NULL, 10, 1, 71, 10, 20, 41, 0, NULL, NULL, NULL, 0),
(777, 'Multiple Choice Single Answer', '&#34;This thing you have done is not good. As the Lord lives, you deserve to die&#34;. This statement is address to', 'CRK', NULL, NULL, 10, 1, 76, 11, 23, 42, 0, NULL, NULL, NULL, 0),
(778, 'Multiple Choice Single Answer', 'Which of the following parables illustrates God&#39;s love? The', 'CRK', NULL, NULL, 10, 1, 72, 20, 3, 49, 0, NULL, NULL, NULL, 0),
(779, 'Multiple Choice Single Answer', 'In the beatitudes, Jesus prescribed that during fasting Christians should', 'CRK', NULL, NULL, 10, 1, 89, 36, 12, 41, 0, NULL, NULL, NULL, 0),
(780, 'Multiple Choice Single Answer', 'The voice from heaven during the baptism of Jesus signifies God&#39;s', 'CRK', NULL, NULL, 10, 1, 80, 34, 3, 43, 0, NULL, NULL, NULL, 0),
(781, 'Multiple Choice Single Answer', 'According to John&#39;s  Gospel, Lazarus was from', 'CRK', NULL, NULL, 10, 1, 71, 28, 6, 37, 0, NULL, NULL, NULL, 0),
(782, 'Multiple Choice Single Answer', 'For Christians, Jesus came that they may', 'CRK', NULL, NULL, 10, 1, 76, 31, 0, 45, 0, NULL, NULL, NULL, 0),
(783, 'Multiple Choice Single Answer', 'During the transfiguration, Moses and Elijah talked to Jesus about', 'CRK', NULL, NULL, 10, 1, 61, 16, 9, 36, 0, NULL, NULL, NULL, 0),
(784, 'Multiple Choice Single Answer', 'At the time Deborah became a judge in Israel, she was a', 'CRK', NULL, NULL, 10, 1, 83, 37, 1, 45, 0, NULL, NULL, NULL, 0),
(785, 'Multiple Choice Single Answer', 'The mission of the seventy signifies mission to', 'CRK', NULL, NULL, 10, 1, 67, 21, 6, 40, 0, NULL, NULL, NULL, 0),
(786, 'Multiple Choice Single Answer', 'Sin has no dominion over those who are under', 'CRK', NULL, NULL, 10, 1, 58, 25, 3, 30, 0, NULL, NULL, NULL, 0),
(787, 'Multiple Choice Single Answer', 'What was Jesus&#39; reaction to the people changing money in the temple?', 'CRK', NULL, NULL, 10, 1, 82, 34, 1, 47, 0, NULL, NULL, NULL, 0),
(788, 'Multiple Choice Single Answer', 'To love one another, according to Jesus is a', 'CRK', NULL, NULL, 10, 1, 64, 23, 1, 40, 0, NULL, NULL, NULL, 0),
(789, 'Multiple Choice Single Answer', 'God&#39;s covenant with Israel on mount Sinai made the people', 'CRK', NULL, NULL, 10, 1, 74, 31, 4, 39, 0, NULL, NULL, NULL, 0),
(790, 'Multiple Choice Single Answer', 'The second account of creation was centred on the creation of', 'CRK', NULL, NULL, 10, 1, 69, 19, 13, 37, 0, NULL, NULL, NULL, 0),
(791, 'Multiple Choice Single Answer', 'According to John, living water means water that', 'CRK', NULL, NULL, 10, 1, 62, 32, 2, 28, 0, NULL, NULL, NULL, 0),
(792, 'Multiple Choice Single Answer', 'The genuineness of faith according to Peter is tested through', 'CRK', NULL, NULL, 10, 1, 77, 14, 14, 49, 0, NULL, NULL, NULL, 0),
(793, 'Multiple Choice Single Answer', 'Hosea described Israel&#39;s relationship with God as that of', 'CRK', NULL, NULL, 10, 1, 76, 25, 8, 43, 0, NULL, NULL, NULL, 0),
(794, 'Multiple Choice Single Answer', 'The immediate consequence of Rehoboam&#39;s rejection of Israel&#39;s request was the', 'CRK', NULL, NULL, 10, 1, 62, 21, 4, 37, 0, NULL, NULL, NULL, 0),
(795, 'Multiple Choice Single Answer', 'The story of Gehazi illustrates the consequence of', 'CRK', NULL, NULL, 10, 1, 66, 25, 2, 39, 0, NULL, NULL, NULL, 0),
(796, 'Multiple Choice Single Answer', 'The message of prophet Amos was mainly about', 'CRK', NULL, NULL, 10, 1, 80, 23, 7, 50, 0, NULL, NULL, NULL, 0),
(797, 'Multiple Choice Single Answer', 'The name Ichabod means', 'CRK', NULL, NULL, 10, 1, 63, 38, 1, 24, 0, NULL, NULL, NULL, 0),
(798, 'Multiple Choice Single Answer', 'In his letter to Philemon, Paul appealed that', 'CRK', NULL, NULL, 10, 1, 65, 15, 8, 42, 0, NULL, NULL, NULL, 0),
(799, 'Multiple Choice Single Answer', 'All the following are some of the spiritual gifts except', 'CRK', NULL, NULL, 10, 1, 66, 22, 2, 42, 0, NULL, NULL, NULL, 0),
(800, 'Multiple Choice Single Answer', '&#34;How is it that you, a Jew, ask a drink of me, a woman of Samaria?&#34; the speaker was surprised because', 'CRK', NULL, NULL, 10, 1, 73, 27, 3, 43, 0, NULL, NULL, NULL, 0),
(801, 'Multiple Choice Single Answer', '&#34;Justification by faith&#34; means', 'CRK', NULL, NULL, 10, 1, 76, 21, 3, 52, 0, NULL, NULL, NULL, 0),
(802, 'Multiple Choice Single Answer', 'The disciples were first called Christians at----', 'CRK', NULL, NULL, 10, 1, 74, 21, 3, 50, 0, NULL, NULL, NULL, 0),
(803, 'Multiple Choice Single Answer', 'Paul&#39;s advises believers to respect those in authority to avoid God&#39;s wrath and also for the sake of', 'CRK', NULL, NULL, 10, 1, 72, 9, 23, 40, 0, NULL, NULL, NULL, 0),
(804, 'Multiple Choice Single Answer', 'How old was Abraham when God appeared to him the 2nd time?', 'CRK', NULL, NULL, 10, 1, 61, 15, 10, 36, 0, NULL, NULL, NULL, 0),
(805, 'Multiple Choice Single Answer', '&#34;An eyes for an eye and a tooth for a tooth&#34;. Jesus corrected the teaching in the statement above by declaring that', 'CRK', NULL, NULL, 10, 1, 76, 33, 2, 41, 0, NULL, NULL, NULL, 0),
(806, 'Multiple Choice Single Answer', 'The sign of God&#39;s covenant with Abraham was----', 'CRK', NULL, NULL, 10, 1, 61, 19, 3, 39, 0, NULL, NULL, NULL, 0),
(807, 'Multiple Choice Single Answer', 'Who among the following did Zerubbabel reject their offer help in rebuilding the temple?', 'CRK', NULL, NULL, 10, 1, 74, 10, 19, 45, 0, NULL, NULL, NULL, 0),
(808, 'Multiple Choice Single Answer', 'The commander of Jabin&#39;s army was', 'CRK', NULL, NULL, 10, 1, 69, 24, 9, 36, 0, NULL, NULL, NULL, 0),
(809, 'Multiple Choice Single Answer', 'God stopped Abraham from sacrificing his son in the land of Moriah because he', 'CRK', NULL, NULL, 10, 1, 65, 27, 0, 38, 0, NULL, NULL, NULL, 0),
(810, 'Multiple Choice Single Answer', 'The disciple who replaced Judas Iscariot was', 'CRK', NULL, NULL, 10, 1, 76, 32, 2, 42, 0, NULL, NULL, NULL, 0),
(811, 'Multiple Choice Single Answer', 'The sins of the sons of Eli was that they treated the offering of the Lord with', 'CRK', NULL, NULL, 10, 1, 79, 29, 0, 50, 0, NULL, NULL, NULL, 0),
(812, 'Multiple Choice Single Answer', 'The message in the parable of the weed is to-----', 'CRK', NULL, NULL, 10, 1, 80, 8, 22, 50, 0, NULL, NULL, NULL, 0),
(813, 'Multiple Choice Single Answer', 'After the death of  Stephen, his garment was dropped at ------feet', 'CRK', NULL, NULL, 10, 1, 80, 24, 8, 48, 0, NULL, NULL, NULL, 0),
(814, 'Multiple Choice Single Answer', 'Who was the father in-law of Moses', 'CRK', NULL, NULL, 10, 1, 69, 29, 1, 39, 0, NULL, NULL, NULL, 0),
(815, 'Multiple Choice Single Answer', 'The proconsul whom Elymas tried to prevent from receiving the gospel was', 'CRK', NULL, NULL, 10, 1, 76, 17, 17, 42, 0, NULL, NULL, NULL, 0),
(816, 'Multiple Choice Single Answer', '&#34;For by one man&#39;s disobedience, many were made sinners.&#34; One man in the above quotation refers to', 'CRK', NULL, NULL, 10, 1, 70, 28, 0, 42, 0, NULL, NULL, NULL, 0),
(817, 'Multiple Choice Single Answer', 'How many stones were picked by Joshua after parting River Jordan', 'CRK', NULL, NULL, 10, 1, 66, 6, 28, 32, 0, NULL, NULL, NULL, 0),
(818, 'Multiple Choice Single Answer', 'Who wanted to buy the holy spirit of God with money?', 'CRK', NULL, NULL, 10, 1, 60, 19, 2, 39, 0, NULL, NULL, NULL, 0),
(819, 'Multiple Choice Single Answer', 'The theme of prophet Amos&#39; message was ---', 'CRK', NULL, NULL, 10, 1, 61, 19, 8, 34, 0, NULL, NULL, NULL, 0),
(820, 'Multiple Choice Single Answer', 'How many lepers came back to Jesus for gratitude', 'CRK', NULL, NULL, 10, 1, 66, 2, 27, 37, 0, NULL, NULL, NULL, 0),
(821, 'Multiple Choice Single Answer', 'Paul was sent as an apostle to', 'CRK', NULL, NULL, 10, 1, 71, 19, 10, 42, 0, NULL, NULL, NULL, 0),
(822, 'Multiple Choice Single Answer', 'The seven deacons of the early church had the primary role of -----', 'CRK', NULL, NULL, 10, 1, 64, 18, 17, 29, 0, NULL, NULL, NULL, 0),
(823, 'Multiple Choice Single Answer', 'How did king Nebudchadnezzar describe the fourth person in the fiery furnace?', 'CRK', NULL, NULL, 10, 1, 73, 28, 13, 32, 0, NULL, NULL, NULL, 0),
(824, 'Multiple Choice Single Answer', 'The sign of walking on the sea proved Jesus&#39;', 'CRK', NULL, NULL, 10, 1, 80, 33, 1, 46, 0, NULL, NULL, NULL, 0),
(825, 'Multiple Choice Single Answer', 'Asa, the king of Judah did what was right in the eye of the lord because he', 'CRK', NULL, NULL, 10, 1, 81, 18, 21, 42, 0, NULL, NULL, NULL, 0),
(826, 'Multiple Choice Single Answer', 'God provided water for the Israelites from a rock at wilderness of', 'CRK', NULL, NULL, 10, 1, 82, 17, 24, 41, 0, NULL, NULL, NULL, 0),
(827, 'Multiple Choice Single Answer', 'The Amalekite king spared by Saul was ------', 'CRK', NULL, NULL, 10, 1, 63, 20, 4, 39, 0, NULL, NULL, NULL, 0),
(828, 'Multiple Choice Single Answer', 'During the reign of King Josiah, the law book was discovered in the Temple by', 'CRK', NULL, NULL, 10, 1, 77, 25, 7, 45, 0, NULL, NULL, NULL, 0),
(829, 'Multiple Choice Single Answer', 'In which country was Jeroboam when Solomon died?', 'CRK', NULL, NULL, 10, 1, 71, 19, 12, 40, 0, NULL, NULL, NULL, 0),
(830, 'Multiple Choice Single Answer', 'The servant of Ahab who saved one hundred prophets of God was', 'CRK', NULL, NULL, 10, 1, 80, 29, 6, 45, 0, NULL, NULL, NULL, 0),
(831, 'Multiple Choice Single Answer', 'Amos was a Shepherd from -----------------', 'CRK', NULL, NULL, 10, 1, 66, 25, 6, 35, 0, NULL, NULL, NULL, 0),
(832, 'Multiple Choice Single Answer', 'God remained faithful to His covenant with Abraham when', 'CRK', NULL, NULL, 10, 1, 77, 33, 2, 42, 0, NULL, NULL, NULL, 0),
(833, 'Multiple Choice Single Answer', 'The contest on mount Carmel was to demonstrate that', 'CRK', NULL, NULL, 10, 1, 67, 31, 2, 34, 0, NULL, NULL, NULL, 0),
(834, 'Multiple Choice Single Answer', 'When David learnt that the child born to him by Bathsheba had died, he', 'CRK', NULL, NULL, 10, 1, 63, 21, 8, 34, 0, NULL, NULL, NULL, 0),
(835, 'Multiple Choice Single Answer', '&#34;Hear this word, you cows of Bashan.............. who oppress the poor, who crush the  needy.............&#34; (Amos 4:1). Cows of Bashan here refer to the.....................................', 'CRK', NULL, NULL, 10, 1, 74, 18, 11, 45, 0, NULL, NULL, NULL, 0),
(836, 'Multiple Choice Single Answer', '&#34;I desire steadfast love and not sacrifice, the knowledge of God, rather than burnt offerings&#34;. This statement was central theme of the prophecy of', 'CRK', NULL, NULL, 10, 1, 70, 9, 26, 35, 0, NULL, NULL, NULL, 0),
(837, 'Multiple Choice Single Answer', 'Saul&#39;s death was mainly because of -----------', 'CRK', NULL, NULL, 10, 1, 66, 22, 1, 43, 0, NULL, NULL, NULL, 0),
(838, 'Multiple Choice Single Answer', 'During the exodus, the old dispensation was sealed with the......................', 'CRK', NULL, NULL, 10, 1, 70, 19, 9, 42, 0, NULL, NULL, NULL, 0),
(839, 'Multiple Choice Single Answer', 'Israel&#39;s patriarch include the following except', 'CRK', NULL, NULL, 10, 1, 82, 23, 5, 54, 0, NULL, NULL, NULL, 0),
(840, 'Multiple Choice Single Answer', 'God&#39;s covenant with Israel on Mount Sinai made the people -------', 'CRK', NULL, NULL, 10, 1, 76, 27, 0, 49, 0, NULL, NULL, NULL, 0),
(841, 'Multiple Choice Single Answer', 'The eating of scroll before prophet Ezekiel was an indication that...................', 'CRK', NULL, NULL, 10, 1, 76, 26, 8, 42, 0, NULL, NULL, NULL, 0),
(842, 'Multiple Choice Single Answer', '&#34;Two nations are in your womb&#34;. The two nations referred to are', 'CRK', NULL, NULL, 10, 1, 55, 8, 11, 36, 0, NULL, NULL, NULL, 0),
(843, 'Multiple Choice Single Answer', 'David family trouble began with incest between', 'CRK', NULL, NULL, 10, 1, 79, 16, 16, 47, 0, NULL, NULL, NULL, 0),
(844, 'Multiple Choice Single Answer', 'The book of Samuel attributes defeat of Israel to', 'CRK', NULL, NULL, 10, 1, 67, 24, 5, 38, 0, NULL, NULL, NULL, 0),
(845, 'Multiple Choice Single Answer', 'The second section of Isaiah is called.................', 'CRK', NULL, NULL, 10, 1, 68, 27, 9, 32, 0, NULL, NULL, NULL, 0),
(846, 'Multiple Choice Single Answer', 'The name Jezreel given to Hosea&#39;s first child was a reference to the revolution of-------', 'CRK', NULL, NULL, 10, 1, 72, 23, 11, 38, 0, NULL, NULL, NULL, 0),
(847, 'Multiple Choice Single Answer', 'The aim of the genealogy of Jesus is to explain that', 'CRK', NULL, NULL, 10, 1, 73, 28, 9, 36, 0, NULL, NULL, NULL, 0),
(848, 'Multiple Choice Single Answer', 'Jesus did not go immediately to attend to Lazarus who was reported sick because He', 'CRK', NULL, NULL, 10, 1, 76, 26, 4, 46, 0, NULL, NULL, NULL, 0),
(849, 'Multiple Choice Single Answer', 'The party that believes more strongly in the Jewish Law is . . .', 'CRK', NULL, NULL, 10, 1, 72, 19, 10, 43, 0, NULL, NULL, NULL, 0),
(850, 'Multiple Choice Single Answer', 'In the synoptic gospels, the attitude of Jesus to the law of Moses was ........................', 'CRK', NULL, NULL, 10, 1, 78, 19, 18, 41, 0, NULL, NULL, NULL, 0);