INSERT INTO `savsoft_qbank` (`qid`, `question_type`, `question`, `description`, `question1`, `description1`, `cid`, `lid`, `no_time_served`, `no_time_corrected`, `no_time_incorrected`, `no_time_unattempted`, `inserted_by`, `inserted_by_name`, `paragraph`, `paragraph1`, `parent_id`) VALUES
(950, 'Multiple Choice Single Answer', 'From the map below, The feature marked J is a', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(951, 'Multiple Choice Single Answer', 'From the map below, The average gradient along the slope marked L-K is approximately', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(952, 'Multiple Choice Single Answer', 'The roads in the area shown on the map below appear to have been constructed mainly to avoid', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(953, 'Multiple Choice Single Answer', 'In the map below, which type of land management is best suited for the area around Aperi?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(954, 'Multiple Choice Single Answer', 'When the map below is enlarged by 2 what is the scale of the map?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(955, 'Multiple Choice Single Answer', 'if the map below is reduced by <sup>1</sup>/<sub>2</sub> what is the new scale?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(956, 'Multiple Choice Single Answer', 'The feature AB in the map below can be described as', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(957, 'Multiple Choice Single Answer', 'The occupation of people in the map area is likely?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(958, 'Multiple Choice Single Answer', 'The crop that can be grown in the South Eastern part of the map below is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(959, 'Multiple Choice Single Answer', 'The contour internal of the map below is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(960, 'Multiple Choice Single Answer', 'The hottest planet is described as', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(961, 'Multiple Choice Single Answer', 'A radio message sent from a location on longitude 15<sup>0</sup>W at 7.00am is received at another location at position of the other location?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(962, 'Multiple Choice Single Answer', 'From a point, the whole circle bearing of a line is 135<sup>0</sup>.   A clockwise angle from the line was measured to be 260<sup>0</sup> to another line.  What is the whole circle bearing of the later line?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(963, 'Multiple Choice Single Answer', 'The stratification of sedimentary rocks is mainly caused by?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(964, 'Multiple Choice Single Answer', 'The most urbanized part of Nigeria is the?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(965, 'Multiple Choice Single Answer', 'In which of the following countries is cotton growing under irrigation the mainstay of the agricultural economy?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(966, 'Multiple Choice Single Answer', 'Which of the following groups of countries constitutes the Chad Basin Commission?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(967, 'Multiple Choice Single Answer', 'An example of a rock formed by wood subjected to pressure and heat is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(968, 'Multiple Choice Single Answer', 'The rocks of the basement complex are generally referred to as', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(969, 'Multiple Choice Single Answer', 'The tropical maritime and tropical continental air masses in Nigeria are responsible for the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(970, 'Multiple Choice Single Answer', 'Which of the following factors has the greatest influence on the mean temperature of a place?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(971, 'Multiple Choice Single Answer', 'A soil that is composed mainly of lion and Alumindim compound is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(972, 'Multiple Choice Single Answer', 'The Instrument used for measuring atmospheric pressure is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(973, 'Multiple Choice Single Answer', 'The direction of flow of ocean currents is determined mainly by the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(974, 'Multiple Choice Single Answer', 'Which of the following minerals is likely to be absent in a reign consisting mainly of igneous and metamorphic rocks?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(975, 'Multiple Choice Single Answer', 'Which of the following is a type of Iron Ore?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(976, 'Multiple Choice Single Answer', 'The highest peak in Nigeria can be found on the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(977, 'Multiple Choice Single Answer', 'An example of argillaceous rock is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(978, 'Multiple Choice Single Answer', 'The rock type whose principal constituents can be seen without magnification is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(979, 'Multiple Choice Single Answer', 'The weight of water vapour contained in a given volume of air is referred to as', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(980, 'Multiple Choice Single Answer', 'A piece of evidence that confirms that the earth is spherical is the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(981, 'Multiple Choice Single Answer', 'The Sudan Savanna vegetation is associated with the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(982, 'Multiple Choice Single Answer', 'A  major characteristic of an Urban settlement is that it is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(983, 'Multiple Choice Single Answer', 'Birth and death rates are often stated as the number of cases per', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(984, 'Multiple Choice Single Answer', 'A poor settlement on the edge of a city is known as a', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(985, 'Multiple Choice Single Answer', 'A desert country which has a high population density supported by irrigation is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(986, 'Multiple Choice Single Answer', 'Which of the following sets of settlements is influenced by the presence of a waterbody?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(987, 'Multiple Choice Single Answer', 'The main mineral composition of lateritic soils are', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(988, 'Multiple Choice Single Answer', 'Shifting cultivation in Agriculture involves', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(989, 'Multiple Choice Single Answer', 'The most sparsely populated areas of the world include', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(990, 'Multiple Choice Single Answer', 'A commercial  agriculture in the topics concentrate on the production of', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(991, 'Multiple Choice Single Answer', 'Wheat is cultivated though irrigation in Nigeria in', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(992, 'Multiple Choice Single Answer', 'The land form marked V is a', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(993, 'Multiple Choice Single Answer', 'If the time in New York (75<sup>0</sup>W) is 5:00pm, the time in Nigeria (15<sup>0</sup>E) will be', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(994, 'Multiple Choice Single Answer', 'Limestone and clay metamorphosed into', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(995, 'Multiple Choice Single Answer', 'Which of the following is a product of volcanicity?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(996, 'Multiple Choice Single Answer', 'The largest ocean in the world is the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(997, 'Multiple Choice Single Answer', 'Hygrometre is used to measure', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(998, 'Multiple Choice Single Answer', 'The temperature at which condensation occurs when air is saturated is the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(999, 'Multiple Choice Single Answer', 'The main process of soil formation in Humid tropics is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1000, 'Multiple Choice Single Answer', 'Which of the following sources of power supply is renewable', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1001, 'Multiple Choice Single Answer', 'What question paper type of Geography is given to you?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1002, 'Multiple Choice Single Answer', 'From the map below: The likely occupation of the people in the area is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1003, 'Multiple Choice Single Answer', 'From the map below: RiverYoo flows towards the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1004, 'Multiple Choice Single Answer', 'From the map below: The bearing of Jodo from Joyo is', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1005, 'Multiple Choice Single Answer', 'From the map below: If the map is enlarged twice the new scale would be?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1006, 'Multiple Choice Single Answer', 'sedimentary rocks are distinguied from other rocks by their?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1007, 'Multiple Choice Single Answer', 'From the map below: The areas with moderate population is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1008, 'Multiple Choice Single Answer', 'From the map below: The area with very low population density is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1009, 'Multiple Choice Single Answer', 'From the map below: The area with high population density', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1010, 'Multiple Choice Single Answer', 'An Imaginary line on the earth&#39;s surface, which divides the earth into two hemisphere, is called', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1011, 'Multiple Choice Single Answer', 'What is true about equinox?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1012, 'Multiple Choice Single Answer', 'In Block mountain features, when one block slips underneath the other rock is termed to be', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1013, 'Multiple Choice Single Answer', 'The lower part of the earth with a continuous zone of basaltic rock forming the ocean floor is made up of â€¦â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1014, 'Multiple Choice Single Answer', 'Latitude 66&#189;<sup>0</sup>S marks the ..............', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1015, 'Multiple Choice Single Answer', 'When faulting caused by tension occurs, it â€¦â€¦â€¦â€¦â€¦â€¦â€¦.', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1016, 'Multiple Choice Single Answer', 'The longitude of London is 0<sup>0</sup> while that of Sydney, Australia is about 150<sup>0</sup>E.What time will it be at Sydney?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1017, 'Multiple Choice Single Answer', 'The distribution of land, ocean bottom, topography basin, air mass and basic composition of the atmosphere makes up â€¦â€¦â€¦â€¦â€¦. Environment.', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1018, 'Multiple Choice Single Answer', 'The direction of rotation or the earth on its axis is from', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1019, 'Multiple Choice Single Answer', 'If the time in town X on longitude 15<sup>0</sup>E is 1.00pm on a Saturday, what will be the time in town Y on the longitude 75<sup>0</sup> W?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1020, 'Multiple Choice Single Answer', 'What is the length of the equatorial diameter of the Earth?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1021, 'Multiple Choice Single Answer', 'Which of the following gas is less abundant in quantity in the atmosphere?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1022, 'Multiple Choice Single Answer', 'The layer of the atmosphere that is cloudless  with extremly thin air without dust, smoke or water vapour is â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1023, 'Multiple Choice Single Answer', 'Mohorivic discontinuity refers to ............?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1024, 'Multiple Choice Single Answer', 'The name given to a wind pattern at the equator is â€¦â€¦â€¦.?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1025, 'Multiple Choice Single Answer', 'The following are the effect of climate change except â€¦â€¦â€¦â€¦â€¦â€¦?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1026, 'Multiple Choice Single Answer', 'Which of the following is not associated with earth movement?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1027, 'Multiple Choice Single Answer', 'When a very long distance is shown by a small map the scale is called â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1028, 'Multiple Choice Single Answer', 'The approximate age of the earth is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1029, 'Multiple Choice Single Answer', 'The Cardinal point are the ............', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1030, 'Multiple Choice Single Answer', 'The actual height of a place above sea level is shown by', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1031, 'Multiple Choice Single Answer', 'Why is the population of most African countries low?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1032, 'Multiple Choice Single Answer', 'A very small settlement with few facilities and homogenous people is called', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1033, 'Multiple Choice Single Answer', 'The most abundant source of energy is .................', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1034, 'Multiple Choice Single Answer', 'Migration affects the population structure of the', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1035, 'Multiple Choice Single Answer', 'The most ecological factor of population distribution is the â€¦â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1036, 'Multiple Choice Single Answer', 'The vital role of the transportation industries in an economy is to', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1037, 'Multiple Choice Single Answer', 'Which of the following is not a factor for the localization of industries', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1038, 'Multiple Choice Single Answer', 'When the earth is at its maximum distance from the sun it is said to be in', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1039, 'Multiple Choice Single Answer', 'The area with very low birth rate corresponds to the areas of â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1040, 'Multiple Choice Single Answer', 'The air transport is more popular in south America because of its â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1041, 'Multiple Choice Single Answer', 'An ecosystem includes', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1042, 'Multiple Choice Single Answer', 'Which of these is a manmade pollutants?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1043, 'Multiple Choice Single Answer', '&#34;Ring of Fire&#34; is another name given to the pacific belt because of  â€¦â€¦â€¦.', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1044, 'Multiple Choice Single Answer', 'The general climate of the equatorial region is â€¦â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1045, 'Multiple Choice Single Answer', 'The term selva refers to ................', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1046, 'Multiple Choice Single Answer', 'Name one of the areas in South America having topical  interior type of climate â€¦â€¦â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1047, 'Multiple Choice Single Answer', 'Which among the following storm is called a typical American storm? â€¦â€¦â€¦â€¦â€¦â€¦', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1048, 'Multiple Choice Single Answer', 'What is the chief restriction on navigation in Africa river? â€¦â€¦â€¦.', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1049, 'Multiple Choice Single Answer', 'The most important occupation in tropical African countries is?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0),
(1050, 'Multiple Choice Single Answer', 'Which area has world single underdeveloped potential of hydroelectricity?', 'GEO', NULL, NULL, 11, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, 0);